# Домашнее задание 5

**Задание 1**

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [48]:
import numpy as np

In [49]:
# если именно как в примере к заданию для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
# то: (n - 1, 0, -1)

n = 10
np.arange(n - 1, 0, -1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [50]:
# если как в описании к заданию "с элементами от числа N до 0"
# то: (n, 0, -1)

n = 21
np.arange(n, 0, -1)

array([21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,
        4,  3,  2,  1])

**Задание 2**

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [51]:
n = 10
diag = np.diag(np.arange(n, 0, -1))
diag

array([[10,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  9,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  8,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  7,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  6,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  5,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  4,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  3,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  2,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1]])

In [52]:
# сумма всех элементов (т.к. матрица диагональная, то учитываться будут только элементы на диагонали)
diag.sum()

55

In [53]:
# сумма элементов на диагонали для любой матрицы
diag.trace()

55

**Задание 3**

Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

In [54]:
import pandas as pd

In [55]:
ratings = pd.read_csv('ratings.csv')
movies = pd.read_csv('movies.csv')

In [56]:
# JOIN ratings с movies
joined = ratings.merge(movies, on='movieId', how='left')
joined.head()

userId  movieId  rating  timestamp                        title  \
0       1        1     4.0  964982703             Toy Story (1995)   
1       1        3     4.0  964981247      Grumpier Old Men (1995)   
2       1        6     4.0  964982224                  Heat (1995)   
3       1       47     5.0  964983815  Seven (a.k.a. Se7en) (1995)   
4       1       50     5.0  964982931   Usual Suspects, The (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                               Comedy|Romance  
2                        Action|Crime|Thriller  
3                             Mystery|Thriller  
4                       Crime|Mystery|Thriller

In [57]:
# фильтрация полученных данных (оценки должны быть равны 5)
# группировка по названию фильма groupby('title') и подсчет строк count()
# сортировка по убыванию sort_values('rating', ascending=False)
# таким образом фильмы с наибольшим количеством оценок 5 будут вверху таблицы 

filtered_ratings = joined[(joined['rating'] == 5)].groupby('title').count().sort_values('rating', ascending=False)
filtered_ratings.head()

userId  movieId  rating  timestamp  \
title                                                                           
Shawshank Redemption, The (1994)              153      153     153        153   
Pulp Fiction (1994)                           123      123     123        123   
Forrest Gump (1994)                           116      116     116        116   
Matrix, The (1999)                            109      109     109        109   
Star Wars: Episode IV - A New Hope (1977)     104      104     104        104   

                                           genres  
title                                              
Shawshank Redemption, The (1994)              153  
Pulp Fiction (1994)                           123  
Forrest Gump (1994)                           116  
Matrix, The (1999)                            109  
Star Wars: Episode IV - A New Hope (1977)     104

In [58]:
# первая строка таблицы с максимальным количеством оценок 5
# не знаю только, как взять отсюда Name 

filtered_ratings.iloc[0]

userId       153
movieId      153
rating       153
timestamp    153
genres       153
Name: Shawshank Redemption, The (1994), dtype: int64

**Задание 4**

По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [59]:
data = pd.read_csv('power.csv')

In [60]:
# фильтрация данных по указанным параметрам 
filtered_data = data[ ((data['country'] == 'Latvia') | (data['country'] == 'Lithuania') | (data['country'] == 'Estonia')) &
                    ((data['category'] == 4) | (data['category'] == 12) | (data['category'] == 21)) &
                    ((data['year'] >= 2005) & (data['year'] <= 2010)) & (data['quantity'] > 0)]
filtered_data.head()

country  year  quantity  category
10617    Estonia  2008       1.0         4
10620    Estonia  2005       1.0         4
11156  Lithuania  2008       1.0         4
11158  Lithuania  2006       1.0         4
11159  Lithuania  2005       1.0         4

In [61]:
# суммирование отфильтрованных данных по параметру quantity
filtered_sum = filtered_data['quantity'].sum()
filtered_sum

240580.0

**Задание 5**

Решите систему уравнений:
\begin{equation*}
\LARGE
4*x + 2*y + z = 4 \\
\LARGE
x + 3*y = 12 \\
\LARGE
5*y + 4*z = -3
\end{equation*}

In [62]:
# коэффициенты в левой части

a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )

In [63]:
# коэффициенты в правой части

b = np.array( [4, 12, -3] )

In [64]:
# решение

from numpy import linalg

In [65]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [66]:
# проверка верности

np.allclose( np.dot(a, linalg.solve(a, b)), b)

True